# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppSquadJavascriptWikitudeSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

xcodeproj 'AppSquadJavascriptWikitudeSwift'
  # Pods for AppSquadJavascriptWikitudeSwift
pod 'AFNetworking', '~> 2.5'
pod 'BDBOAuth1Manager'
pod 'SwiftyJSON'
  target 'AppSquadJavascriptWikitudeSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppSquadJavascriptWikitudeSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
