# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartStreet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

project 'SmartStreet'

  # Pods for SmartStreet
pod 'AFNetworking', '~> 2.5'
pod 'BDBOAuth1Manager'
pod 'SwiftyJSON'
# Pods for temp
  target 'SmartStreetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmartStreetUITests' do
    inherit! :search_paths
    # Pods for testing

  end

end
